### ISSUE TITLE
Check if it is possible to switch from commandLink to commandButton in some cases

### ISSUE THREAD

**Issue by madryk** [CeON/fairchive#1144]

**Comment by sudmar** [comment]
A sample way of converting `commandLink` to `commandButton`, using the dashboard Licenses page as an example.

Before changes:

```
<p:commandLink onclick="primeFacesShowModal('newLicense', this);" styleClass="btn btn-default btn-access">
    <span class="glyphicon glyphicon-plus"/> #{bundle['dashboard.license.newLicense.add']}
</p:commandLink>
```

After changes;

```
<p:commandButton onclick="primeFacesShowModal('newLicense', this);" 
    styleClass="btn"
    icon="glyphicon glyphicon-plus"
    value="#{bundle['dashboard.license.newLicense.add']}" />
```

Basically, the process goes as follows:
- the classes from the glyphicon's `span` tag are transferred to the `icon` attribute.
- the `commandLink` content other that the aforementioned `span` (ie. button label) is transferred to the `value` attribute.
- the classes `btn-default btn-access` aren't necessary anymore, but they shouldn't break anything either.
- every other attribute should just be copied over.
- for buttons without a label, don't include the `value` attribute.
- for buttons without an icon, don't include the `icon` attribute.

As far as I can tell, this should convert `commandLink` to `commandButton`, leaving the styling and functionality intact.  On dashboard's licenses page, there are now a `commandLink` Reorder and `commandButton` Add next to each other, to show that the styling is the same. If I understand correctly, the Reorder button doesn't need to be converted to `commandButton`, since it  redirects to another page (ie. acts as a link).
