### ISSUE TITLE
Explore how we obtain information regarding file formats and how do we make use of it in the app

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1319]

**Comment by wfenrich** [comment]
We would like to check the file format of deposited files. To make it reasonably, we should first figure out how file format is currently established (through Dataverse, a browser, in some other manner?) and what do we do with this knowledge within application?

**Comment by tomaszblazejczyk** [comment]
1. After successful file upload basic information is mime type provided by browser. 
2. Then try to determine specific format - first step is tabular format check from set of POR, SAV, DTA, RDA.
3. If no tabular format detected check GraphML format then set fileType as "text/xml-graphml"
4. If no GraphML then check if FITS file then set type as "application/fits"
5. If still no file type detected then check file with JHove engine which has following modules configured:

<class>edu.harvard.hul.ois.jhove.module.AiffModule</class>
<class>edu.harvard.hul.ois.jhove.module.WaveModule</class>
<class>edu.harvard.hul.ois.jhove.module.PdfModule</class>
<class>edu.harvard.hul.ois.jhove.module.Jpeg2000Module</class>
<class>edu.harvard.hul.ois.jhove.module.JpegModule</class>
<class>edu.harvard.hul.ois.jhove.module.GifModule</class>
<class>edu.harvard.hul.ois.jhove.module.TiffModule</class>
<class>edu.harvard.hul.ois.jhove.module.HtmlModule</class>
<class>edu.harvard.hul.ois.jhove.module.AsciiModule</class>
<class>edu.harvard.hul.ois.jhove.module.Utf8Module</class>

6. Additional processing - based on JHove mime result "text/plain" or "application/octet-stream" determine if statistical file type by extension from map:

".do", "application/x-stata-syntax"
".sas", "application/x-sas-syntax"
".sps", "application/x-spss-syntax"
".csv", "text/csv"
".tsv", "text/tsv"

and from "/META-INF/mimetypes.default" config file if any exists in classpath

7. If file type indicates archive file "application/x-gzip" then check if content has FITS data - then set file type as "application/fits-gzipped"

8. If file type indicates archive file "application/zip" then check if content has Shapefile data - then set file type as "application/zipped-shapefile" otherwise, if we are going to save unpacked content, unpack all files and determine its types performing steps described above.

9. if still no type detected then set type as "application/octet-stream"

**Comment by tomaszblazejczyk** [comment]
ContentType is property of DataFile and is used in several pages - mostly for proper presentation of downloadable datafiles or determine widget for data preview
