### ISSUE TITLE
Explore if/how citation and the display of search results are related for datasets and files, local as well as harvested

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1353]

**Comment by MrK191** [comment]
datasetPage - it is taken from DataCitation class at the end.
search results - taken from solr citationHtml if available otherwise citation field.
filePage - it is taken from DataCitation class at the end.

Harvesting - HarvesterServiceBean#processRecord > FastGetRecord#runGetRecord > ImportServiceBean#doImportHarvestedDataset - ddi/dcTo/Json > JsonParser#parseDataset

supported formats - ddi/oai_ddi/^oai_ddi.*
dc/oai_dc
dataverse_json
