### ISSUE TITLE
It should be possible to set a limit for the maximum size of the batch of files uploaded via GUI

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#1962]
Without the limit, an ample batch may exceed the amount of space available on server and clog the repository. :(

**Comment by MrK191** [comment]
So the main idea was to attach yourself with JS in order to find out whats the size of uploaded files, this part was successful, you can send names and their size in loop to the backend. There is a catch that method in JS must be in 'setTimeout' otherwise the DOM is not updated properly yet and array return incorrect length. The main problem is that I didn't find a way to attach myself to remove file during upload operation, which is necessary to update HashMap in backend. Another way I tried was to attach myself to 'onAdd' function but again I didn't find a way to access uploaded files information.

**Comment by MrK191** [comment]
https://stackoverflow.com/questions/52410786/how-to-get-selected-files-from-pfileupload-after-selection-and-before-uploading?rq=1 - Tried it but also didn't worked for me. Maybe I missed something.

**Comment by MrK191** [comment]
So capturing cancel click didn't work
```
$(document).ready(function () {
            uploadWidgetDropMsg();

            $(".ui-fileUpload-cancel").click(function () {
                console.log("CAPTURED CLICK 2");
            });

        })
```
