### ISSUE TITLE
Fix grey bar on drodb wordpress

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2006]
It occured a few months ago after theme update.

**Comment by wfenrich** [comment]
![image](https://user-images.githubusercontent.com/8678301/134481411-c35f9789-b8b0-49b3-9228-ad37daca148e.png)

**Comment by sudmar** [comment]
@madryk here are the changes:

```
/* Fix grey bar under menu */
.custom-header-media::before {
	background: none;
}

/* Add a fallback header bacgkround color */
.custom-header {
	background: #2ba7df;
}

/* Add shadow to header contents to improve legibility */
.site-title {
	text-shadow: 2px 2px #000;
}
.site-description {
	text-shadow: 1px 1px #000;
}
.custom-logo {
	-webkit-filter: drop-shadow(2px 2px rgba(0,0,0,0.75));
	filter: drop-shadow(2px 2px rgba(0,0,0,0.75));
}

/* Fix header background position on subpages */
.has-header-image:not(.twentyseventeen-front-page):not(.home) .custom-header-media img {
	position: fixed;
}
```

The grey bar was a part of a default header background, which overflowed. It was disabled, and a different fallback background was specified (in case the user has disabled images). `#2ba7df` is the drodb theme color.

A shadow was added to the text in the header, in an attempt to improve its legibility somewhat.

The header background position was fixed so that it's consistent on the home page and subpgaes; I have no idea whether this was a bug or a feature, but it looked a bit odd to me.
