### ISSUE TITLE
User should be able to download via API CSV with download URL-s for all unrestricted files in a dataset version

### ISSUE THREAD

**Issue by wfenrich** [CeON/fairchive#2418]
The CSV should consist of 3 columns: 

* File name
* Open Access (TRUE/FALSE)
* Download URL

As we do not show download URL-s for restricted files (filees that are NOT open access), for consistency we should not show them in the CSV as well.

API should allow user to indicate dataset version directly (so for instance 1.0, 1.1, 2.0 etc.), as well as the latest version of the dataset.  

It should NOT be possible to use this endpoint for dataset that are under embargo and draft version.

**Comment by wfenrich** [comment]
A thing to consider: maybe we should keep restricted files in the csv, just without URLs?

Yes, we should keep them, but wit information that they are not Open Access and without URL.

**Comment by diasf** [comment]
API url example to retrieve the CSV: 

`curl -X GET http://localhost:8080/api/datasets/:persistentId/versions/:latest-published/files/urls?persistentId=doi:10.5072/FK2/3EH02Z`

With:
`:latest-published` : Use the latest published version. Can be replaced by a specific version number (eg. 1, 1.2, ..). 
`:persistentId` : Indicates to use the `persistentId` query parameter in the url. So that complex identifiers can be used. `:latest` can be replaced by database internal numerical id (and then also without `persistentId` query parameter).

Similar to unreleased datasets, those with enabled guestbook cannot be downloaded as well.
